# Generated by Django 3.2.6 on 2021-08-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала мероприятия')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания мероприятия')),
                ('image', models.ImageField(blank=True, upload_to='posters', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Постер',
                'verbose_name_plural': 'Постеры',
                'ordering': ['pk'],
            },
        ),
    ]
