# Generated by Django 3.2.6 on 2021-08-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=150, verbose_name='Тип билета')),
                ('ticket_price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.AddField(
            model_name='posters',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Адрес мероприятия'),
        ),
        migrations.AddField(
            model_name='posters',
            name='scheme',
            field=models.ImageField(blank=True, upload_to='scheme/', verbose_name='Схема'),
        ),
        migrations.AddField(
            model_name='posters',
            name='title_address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название места мероприятия'),
        ),
        migrations.AlterField(
            model_name='posters',
            name='image',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='posters',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='posters.ticket', verbose_name='Билет и цена'),
        ),
    ]
